import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex justify-center items-center">
        <div>
          <div className='flex gap-2 justify-center w-[15rem] mb-2'>
            <input className='bg-white rounded py-2 border-[0.1rem] border-black/100 outline-none'/>
            <button className='bg-black text-white px-2 rounded'>Create</button>
          </div>
          <ul className='flex flex-col gap-2 h-[30rem] overflow-y-auto'>
            <li className='px-3 py-5 bg-gradient-to-tr from-pink-600 to-indigo-500 text-slate-50 w-[15rem] rounded shadow'>Post 1</li>
            <li className='px-3 py-5 bg-gradient-to-tr from-pink-600 to-indigo-500 text-slate-50 w-[15rem] rounded shadow'>Post 2</li>
            <li className='px-3 py-5 bg-gradient-to-tr from-pink-600 to-indigo-500 text-slate-50 w-[15rem] rounded shadow'>Post 3</li>
            <li className='px-3 py-5 bg-gradient-to-tr from-pink-600 to-indigo-500 text-slate-50 w-[15rem] rounded shadow'>Post 4</li>
            <li className='px-3 py-5 bg-gradient-to-tr from-pink-600 to-indigo-500 text-slate-50 w-[15rem] rounded shadow'>Post 5</li>
          </ul>
        </div>
       
      </main>
    </>
  )
}
